import type { Product } from "@/types/product";

/* UI-only Arabic copy. Catalog identifiers and commerce payloads stay unchanged. */
export const arabicUi: Record<string, string> = {
  "DAILY FLASH DEALS": "عروض يومية سريعة",
  "24H PICKS": "اختيارات ٢٤ ساعة",
  "FREE SHIPPING ON ORDERS OVER 2,500 EGP": "شحن مجاني للطلبات فوق ٢٬٥٠٠ جنيه",
  "HIGH QUALITY": "جودة عالية",
  "REAL RESULTS": "نتائج حقيقية",
  "TRUSTED BRANDS": "علامات موثوقة",
  "A HEALTHIER TOMORROW": "غد أكثر صحة",
  "Search all of Vi2": "ابحث في Vi2",
  "ACCOUNT": "الحساب", "SIGN IN": "تسجيل الدخول", "SIGN OUT": "تسجيل الخروج",
  "Supplements": "المكملات", "Sports Nutrition": "التغذية الرياضية",
  "Vitamins & Minerals": "الفيتامينات والمعادن", "Wellness": "العافية",
  "Brands": "العلامات التجارية", "Health Goals": "الأهداف الصحية",
  "Deals": "العروض", "Best Sellers": "الأكثر مبيعاً", "New": "جديد", "Bundles": "الباقات",
  "LIVE WELL, LIVE FULLY.": "عِش بصحة، عِش حياتك كاملة.",
  "LIVE WELL,": "عِش بصحة،", "LIVE FULLY.": "عِش حياتك كاملة.",
  "LIVE WELL,LIVE FULLY.": "عِش بصحة، عِش حياتك كاملة.",
  "PREMIUM SUPPLEMENTSFOR A STRONGER, HEALTHIER YOU.": "مكملات متميزة لحياة أقوى وأكثر صحة.",
  "SUPPLEMENTS FOR A BRIGHTER YOU": "مكملات ليوم أكثر إشراقاً",
  "VI2 PICKS": "اختيارات Vi2", "TRENDING NOW": "الأكثر رواجاً الآن", "VIEW ALL": "عرض الكل",
  "POPULAR RIGHT NOW": "الأكثر طلباً الآن", "BEST SELLERS": "الأكثر مبيعاً",
  "VITAMINS & MINERALS": "الفيتامينات والمعادن", "SPORTS NUTRITION": "التغذية الرياضية",
  "WELLNESS": "العافية", "SHOP BY HEALTH GOAL": "تسوق حسب الهدف الصحي",
  "START WITH WHAT YOU NEED.": "ابدأ بما تحتاجه.",
  "Real health. Real progress. A stronger you.": "صحة حقيقية. تقدم حقيقي. نسخة أقوى منك.",
  "IMMUNE SUPPORT": "دعم المناعة", "Everyday defense": "حماية يومية",
  "GUT HEALTH": "صحة الجهاز الهضمي", "Feel better daily": "راحة أفضل كل يوم",
  "ENERGY & FITNESS": "الطاقة واللياقة", "Fuel your day": "طاقة تدوم طوال يومك",
  "STRONGER EVERYDAY": "أقوى كل يوم", "MUSCLE & RECOVERY": "العضلات والاستشفاء",
  "Build. Repair. Perform.": "ابنِ. تعافَ. تألق.", "HEART HEALTH": "صحة القلب",
  "For a healthier tomorrow": "لغد أكثر صحة", "STRESS & SLEEP": "التوتر والنوم",
  "A calmer, better you": "هدوء أكبر وحياة أفضل", "VI2 GOAL PICK": "اختيار Vi2 لهدفك",
  "Protein, creatine and recovery support for stronger training days.": "دعم بالبروتين والكرياتين والاستشفاء لأيام تدريب أقوى.",
  "SHOP NOW": "تسوق الآن", "VI2 VALUE SETS": "باقات Vi2 الموفّرة",
  "BUILD A ROUTINE.": "ابنِ روتينك.", "SHOP INDIVIDUALLY": "تسوق كل منتج منفرداً",
  "TRAIN + BUILD": "تدرّب + ابنِ", "STRENGTH ROUTINE": "روتين القوة",
  "Creatine and whey together for a simple training routine.": "الكرياتين والواي معاً لروتين تدريب بسيط.",
  "EVERYDAY WELLNESS": "عافية يومية", "DAILY ESSENTIALS": "الأساسيات اليومية",
  "A simple daily pairing for general wellness support.": "ثنائي يومي بسيط لدعم العافية العامة.",
  "REST + RECOVERY": "راحة + استشفاء", "CALM + RECOVER": "اهدأ + تعافَ",
  "Magnesium and ashwagandha in one recovery-focused set.": "المغنيسيوم والأشواجاندا في باقة واحدة للاستشفاء.",
  "ADD SET": "أضف الباقة", "VI2 · DIETARY & WELLNESS SUPPLEMENTS": "VI2 · مكملات غذائية ومنتجات للعافية",
  "Dietary, wellness and sports nutrition selected around quality, simplicity and everyday living.": "مكملات غذائية ومنتجات للعافية والتغذية الرياضية مختارة بعناية للجودة والبساطة والحياة اليومية.",
  "SHOP": "المتجر", "All products": "كل المنتجات", "About us": "من نحن",
  "Authenticity": "الأصالة", "Shipping": "الشحن", "Returns": "الاسترجاع", "Contact": "تواصل معنا",
  "FOLLOW": "تابعنا", "Dietary & Wellness Supplements": "مكملات غذائية ومنتجات للعافية", "Egypt": "مصر",
  "YOUR BAG": "حقيبتك", "Cart": "السلة", "Your bag is empty.": "حقيبتك فارغة.",
  "Discover sports nutrition, wellness essentials and everyday supplements.": "اكتشف التغذية الرياضية وأساسيات العافية والمكملات اليومية.",
  "SHOP PRODUCTS": "تسوق المنتجات", "Close cart": "إغلاق السلة",
  "Decrease quantity": "تقليل الكمية", "Increase quantity": "زيادة الكمية", "Subtotal": "المجموع الفرعي",
  "Delivery is calculated at checkout.": "يتم احتساب التوصيل عند إتمام الطلب.", "CHECKOUT": "إتمام الطلب",
  "VI2 COLLECTION": "مجموعة Vi2",
  "Search by product, brand, category or health goal — then narrow the catalog without slowing down the buying flow.": "ابحث حسب المنتج أو العلامة أو الفئة أو الهدف الصحي، ثم صفِّ النتائج بسهولة.",
  "Search products, brands, goals...": "ابحث عن منتجات أو علامات أو أهداف...", "Search products": "البحث في المنتجات",
  "Clear search": "مسح البحث", "FILTERS": "الفلاتر", "SORT": "الترتيب", "Featured": "المميزة",
  "Price: Low to High": "السعر: من الأقل إلى الأعلى", "Price: High to Low": "السعر: من الأعلى إلى الأقل",
  "Highest Rated": "الأعلى تقييماً", "POPULAR:": "الأكثر بحثاً:", "FILTER": "تصفية", "RESET": "إعادة ضبط",
  "HEALTH GOAL": "الهدف الصحي", "All Goals": "كل الأهداف", "Immune Support": "دعم المناعة",
  "Gut Health": "صحة الجهاز الهضمي", "Muscle & Recovery": "العضلات والاستشفاء",
  "Energy & Fitness": "الطاقة واللياقة", "Heart Health": "صحة القلب", "Stress & Sleep": "التوتر والنوم",
  "Daily Wellness": "العافية اليومية", "CATEGORY": "الفئة", "All": "الكل", "Pre-Workout": "قبل التمرين",
  "Mass Gainer": "زيادة الكتلة", "BRAND": "العلامة التجارية", "All Brands": "كل العلامات",
  "FORM": "الشكل", "All Forms": "كل الأشكال", "Powder": "مسحوق", "Tablets": "أقراص",
  "Capsules": "كبسولات", "Softgels": "كبسولات هلامية", "DIET": "النظام الغذائي",
  "All Diets": "كل الأنظمة", "Vegan": "نباتي", "Keto": "كيتو", "Non-GMO": "غير معدل وراثياً",
  "ALLERGEN-FREE": "خالٍ من مسببات الحساسية", "All Allergen Filters": "كل فلاتر الحساسية",
  "Gluten-Free": "خالٍ من الجلوتين", "Dairy-Free": "خالٍ من الألبان", "Soy-Free": "خالٍ من الصويا",
  "IN STOCK ONLY": "المتوفر فقط",
  "Verified dietary attributes must be supplied per SKU before launch.": "يجب توفير بيانات النظام الغذائي الموثقة لكل منتج قبل الإطلاق.",
  "Verified manufacturer allergen data is required per SKU before launch.": "يجب توفير بيانات الحساسية الموثقة من المصنع لكل منتج قبل الإطلاق.",
  "IN STOCK": "متوفر", "OUT OF STOCK": "غير متوفر", "FEATURED": "مميز", "BEST SELLER": "الأكثر مبيعاً",
  "PRODUCT": "منتج", "PRODUCTS": "منتجات", "Best Seller": "الأكثر مبيعاً",
  "Vi2 Pick": "اختيار Vi2", "Everyday Essential": "أساسي يومي", "Popular": "رائج",
  "Top Rated": "الأعلى تقييماً", "Premium": "متميز", "Sports": "رياضي", "Trending": "رائج الآن",
  "Premium Protein": "بروتين متميز", "New at Vi2": "جديد لدى Vi2",
  "VI2 PICK": "اختيار Vi2", "EVERYDAY ESSENTIAL": "أساسي يومي", "POPULAR": "رائج", "TOP RATED": "الأعلى تقييماً",
  "PREMIUM": "متميز", "SPORTS": "رياضي", "TRENDING": "رائج الآن", "PREMIUM PROTEIN": "بروتين متميز",
  "NEW AT VI2": "جديد لدى Vi2", "NO MATCHES": "لا توجد نتائج", "Nothing found.": "لم نعثر على نتائج.",
  "Try another product, health goal, category or brand.": "جرّب منتجاً أو هدفاً صحياً أو فئة أو علامة أخرى.",
  "VIEW ALL PRODUCTS": "عرض كل المنتجات", "VI2 CATALOG": "كتالوج Vi2", "FILTER PRODUCTS": "تصفية المنتجات",
  "Product filters": "فلاتر المنتجات", "Close filters": "إغلاق الفلاتر", "Home": "الرئيسية", "Shop": "المتجر",
  "FACTS": "الحقائق", "SERVINGS": "حصة", "PACKAGE": "العبوة", "QUALITY": "الجودة", "By": "من", "reviews": "مراجعة",
  "PACKAGE QUANTITY": "كمية العبوة", "1 PACK": "عبوة واحدة", "KEY INFO": "معلومات أساسية",
  "TOTAL SERVINGS": "إجمالي الحصص", "PACKAGE SIZE": "حجم العبوة", "STOCK": "المخزون",
  "QUALITY & PRODUCT DATA": "بيانات الجودة والمنتج", "AUTHENTICITY FOCUSED": "تركيز على الأصالة",
  "LAB DATA READY": "بيانات المختبر جاهزة", "BATCH INFO READY": "بيانات التشغيلة جاهزة",
  "SIMILAR RECOMMENDATION": "اقتراح مشابه", "VIEW": "عرض", "OUR PRICE": "سعرنا", "In Stock": "متوفر",
  "ONE-TIME PURCHASE": "شراء لمرة واحدة", "SUBSCRIBE & SAVE": "اشترك ووفر", "ADD TO CART": "أضف إلى السلة",
  "BUY NOW": "اشترِ الآن", "FAST SHIPPING": "شحن سريع", "Free over 2,500 EGP": "مجاني فوق ٢٬٥٠٠ جنيه",
  "PRODUCT INFORMATION": "معلومات المنتج", "SUPPLEMENT FACTS": "حقائق المكمل",
  "QUALITY, BATCH & COMPLIANCE": "الجودة والتشغيلة والامتثال", "DELIVERY & RETURNS": "التوصيل والاسترجاع",
  "RELATED CATEGORIES": "فئات ذات صلة", "DISCOVER MORE": "اكتشف المزيد",
  "SIMILAR ITEMS TO CONSIDER": "منتجات مشابهة قد تناسبك", "STACKABLE VALUE SET": "باقة متكاملة موفرة",
  "COMPLETE THE ROUTINE.": "أكمل روتينك.",
  "Add products sharing the same health goal in one step. Final promotion rules can be connected to the commerce backend later.": "أضف منتجات تشترك في الهدف الصحي نفسه بخطوة واحدة، مع بقاء قواعد العروض التجريبية كما هي.",
  "SET TOTAL": "إجمالي الباقة", "ADD ROUTINE": "أضف الروتين", "VERIFIED-BUYER REVIEWS": "مراجعات مشترين موثقة",
  "Review profiles can include age group, health goal and product images so shoppers can understand who a product worked for.": "قد تتضمن المراجعات الفئة العمرية والهدف الصحي وصور المنتج لمساعدة المتسوقين على فهم التجربة.",
  "Verified-purchase tagging is prepared for the final customer-order system.": "ميزة توثيق الشراء جاهزة للربط بنظام الطلبات مستقبلاً.",
  "SHARE YOUR EXPERIENCE": "شارك تجربتك", "WRITE A REVIEW": "اكتب مراجعة", "REVIEW FORM COMPLETED": "اكتمل نموذج المراجعة",
  "YOUR RATING": "تقييمك", "AGE GROUP": "الفئة العمرية", "Select age group": "اختر الفئة العمرية",
  "Select health goal": "اختر الهدف الصحي", "YOUR REVIEW": "مراجعتك", "ADD PRODUCT IMAGE": "أضف صورة للمنتج",
  "JPG or PNG · optional": "JPG أو PNG · اختياري", "SUBMIT REVIEW": "إرسال المراجعة", "AUTHENTIC PRODUCTS": "منتجات أصلية",
  "Carefully selected for Vi2.": "مختارة بعناية لدى Vi2.", "SECURE PACKAGING": "تغليف آمن",
  "Prepared carefully for delivery.": "مجهزة بعناية للتوصيل.", "ACROSS EGYPT": "في جميع أنحاء مصر",
  "Simple local delivery experience.": "تجربة توصيل محلية سهلة.", "Wellness made easier.": "العافية أصبحت أسهل.",
  "BACK": "رجوع", "DETAILS": "التفاصيل", "CONFIRM": "التأكيد", "COMPLETE": "مكتمل",
  "SECURE CHECKOUT": "إتمام طلب آمن", "ORDER SUMMARY": "ملخص الطلب", "ORDER": "الطلب",
  "ITEM": "منتج", "ITEMS": "منتجات", "DELIVERY": "التوصيل", "FREE": "مجاني", "TOTAL": "الإجمالي",
  "SUMMARY": "الملخص", "ratings": "تقييم", "LIVE FULLY": "عِش حياتك كاملة",
  "Checkout progress": "تقدم إتمام الطلب", "Search Vi2": "البحث في Vi2", "CONFIRM YOUR ORDER": "أكد طلبك",
  "CHOOSE ONE": "اختر طريقة", "EGP TO GO": "جنيه متبقي",
  "FAST.": "سريع.", "SIMPLE.": "وبسيط.",
  "Add your delivery details, review your order, and place it in the next step.": "أضف بيانات التوصيل، راجع طلبك ثم أكده في الخطوة التالية.",
  "STEP 01": "الخطوة ٠١", "STEP 02": "الخطوة ٠٢", "CONTACT INFORMATION": "بيانات التواصل",
  "WHO ARE WE DELIVERING TO?": "لمن سيتم التوصيل؟", "FULL NAME *": "الاسم الكامل *", "Your full name": "اسمك الكامل",
  "PHONE NUMBER *": "رقم الهاتف *", "EMAIL": "البريد الإلكتروني", "DELIVERY ADDRESS": "عنوان التوصيل",
  "WHERE SHOULD IT GO?": "إلى أين نرسل الطلب؟", "GOVERNORATE *": "المحافظة *", "Select Governorate": "اختر المحافظة",
  "Cairo": "القاهرة", "Giza": "الجيزة", "Alexandria": "الإسكندرية", "Qalyubia": "القليوبية",
  "Sharqia": "الشرقية", "Dakahlia": "الدقهلية", "Gharbia": "الغربية", "Monufia": "المنوفية",
  "Beheira": "البحيرة", "Fayoum": "الفيوم", "Beni Suef": "بني سويف", "Minya": "المنيا",
  "Assiut": "أسيوط", "Sohag": "سوهاج", "Qena": "قنا", "Luxor": "الأقصر", "Aswan": "أسوان",
  "Red Sea": "البحر الأحمر", "Suez": "السويس", "Ismailia": "الإسماعيلية", "Port Said": "بورسعيد",
  "AREA / DISTRICT *": "المنطقة / الحي *", "Area / district": "المنطقة / الحي",
  "DETAILED ADDRESS *": "العنوان بالتفصيل *", "Building, street, floor and apartment": "المبنى والشارع والطابق والشقة",
  "DELIVERY NOTES": "ملاحظات التوصيل", "STANDARD DELIVERY": "توصيل عادي", "Standard Delivery": "توصيل عادي",
  "Delivery across Egypt": "توصيل إلى جميع أنحاء مصر", "CONTINUE TO CONFIRMATION": "متابعة إلى التأكيد",
  "Please complete all required fields.": "يرجى إكمال جميع الحقول المطلوبة.",
  "Your order is empty. Add a product before continuing.": "طلبك فارغ. أضف منتجاً قبل المتابعة.",
  "Enter a valid Egyptian mobile number, for example 01012345678.": "أدخل رقم هاتف مصرياً صحيحاً، مثل 01012345678.",
  "The order service is temporarily unavailable. Please try again.": "خدمة الطلبات غير متاحة مؤقتاً. حاول مرة أخرى.",
  "Could not place your order. Please try again.": "تعذر تنفيذ طلبك. حاول مرة أخرى.",
  "REVIEW & PLACE ORDER": "راجع وأكد الطلب", "YOUR ORDER": "طلبك",
  "Check the details below, choose your payment method, then place your order.": "راجع البيانات التالية، واختر طريقة الدفع ثم أكد طلبك.",
  "PAYMENT METHOD": "طريقة الدفع", "CASH ON DELIVERY": "الدفع عند الاستلام",
  "Pay when your order arrives": "ادفع عند وصول طلبك", "INSTAPAY / BANK": "إنستاباي / تحويل بنكي",
  "Transfer after checkout": "حوّل بعد إتمام الطلب", "DEBIT / CREDIT CARD": "بطاقة خصم / ائتمان",
  "Card payment": "الدفع بالبطاقة",
  "This order will be created with payment status pending until the payment flow is connected.": "سيتم إنشاء الطلب بحالة دفع معلقة حتى يتم ربط مسار الدفع.",
  "ORDER REVIEW": "مراجعة الطلب", "VERIFY DETAILS": "تحقق من البيانات", "EDIT": "تعديل",
  "Free delivery": "توصيل مجاني", "Across Egypt": "في جميع أنحاء مصر", "Pay on arrival": "الدفع عند الوصول",
  "Payment pending": "الدفع معلق", "PLACING ORDER...": "جارٍ تأكيد الطلب...", "PLACING...": "جارٍ التأكيد...",
  "PLACE ORDER": "تأكيد الطلب", "Secure checkout. No account required.": "إتمام طلب آمن. لا يلزم حساب.",
  "Your order is empty.": "طلبك فارغ.", "RETURN TO SHOP": "العودة إلى المتجر", "FREE DELIVERY": "توصيل مجاني",
  "Delivery": "التوصيل", "Delivery across Egypt.": "توصيل إلى جميع أنحاء مصر.",
  "Please complete all required delivery details.": "يرجى إكمال جميع بيانات التوصيل المطلوبة.",
  "Please select a valid payment method.": "يرجى اختيار طريقة دفع صحيحة.", "The order totals are invalid.": "إجماليات الطلب غير صحيحة.",
  "One or more order items are invalid.": "بيانات منتج واحد أو أكثر غير صحيحة.",
  "Could not create your order. Please try again.": "تعذر إنشاء طلبك. حاول مرة أخرى.",
  "01 DETAILS": "٠١ التفاصيل", "02 CONFIRM": "٠٢ التأكيد", "03 COMPLETE": "٠٣ مكتمل",
  "ORDER RECEIVED": "تم استلام الطلب", "STAGE 03 / COMPLETE": "المرحلة ٠٣ / مكتمل",
  "RECEIVED.": "تم استلامه.", "THANK YOU": "شكراً لك", "ORDER REFERENCE": "رقم الطلب",
  "ORDER REGISTERED": "تم تسجيل الطلب", "Your order has been saved and is ready for the next fulfillment step.": "تم حفظ طلبك وهو جاهز للخطوة التالية من التجهيز.",
  "DELIVERY ACROSS EGYPT": "توصيل إلى جميع أنحاء مصر", "We’ll use the delivery details you entered at checkout.": "سنستخدم بيانات التوصيل التي أدخلتها عند إتمام الطلب.",
  "DESTINATION": "وجهة التوصيل", "Customer": "العميل", "CONTACT": "التواصل", "PAYMENT": "الدفع",
  "InstaPay / Bank Transfer": "إنستاباي / تحويل بنكي", "Debit / Credit Card": "بطاقة خصم / ائتمان",
  "Cash on Delivery": "الدفع عند الاستلام", "We’ll use this number for order updates.": "سنستخدم هذا الرقم لإرسال تحديثات الطلب.",
  "Payment due according to selected method": "الدفع مستحق حسب الطريقة المختارة",
  "CONTINUE SHOPPING": "متابعة التسوق", "BACK HOME": "العودة للرئيسية",
  "Keep your order reference for your records.": "احتفظ برقم الطلب في سجلاتك.", "RECEIPT SUMMARY": "ملخص الإيصال",
  "VI2 ACCOUNT": "حساب Vi2", "YOUR WELLNESS.": "عافيتك.",
  "Accounts can add points, order history, faster reordering and personalized benefits — while guest checkout stays available.": "يمنحك الحساب نقاطاً وسجل طلبات وإعادة شراء أسرع ومزايا مخصصة، مع بقاء الشراء كزائر متاحاً.",
  "VI2 POINTS": "نقاط Vi2", "Points preview based on eligible orders stored in this browser.": "معاينة للنقاط بناءً على الطلبات المؤهلة المحفوظة في هذا المتصفح.",
  "ACCOUNT BENEFITS": "مزايا الحساب", "Saved details, points and a faster return visit.": "بيانات محفوظة ونقاط وزيارة عودة أسرع.",
  "ORDER HISTORY": "سجل الطلبات", "Keep purchases organized in one place.": "احتفظ بمشترياتك منظمة في مكان واحد.",
  "BUY IT AGAIN": "اشترِه مرة أخرى", "Reorder routine products with fewer steps.": "أعد طلب منتجات روتينك بخطوات أقل.",
  "QUICK REPLENISH": "إعادة شراء سريعة", "SHOP ALL": "تسوق الكل", "ADD AGAIN": "أضف مجدداً",
  "NO LOCAL ORDER YET": "لا يوجد طلب محفوظ بعد", "YOUR NEXT ROUTINE STARTS HERE.": "روتينك التالي يبدأ هنا.",
  "Once an order is placed, its products can appear here for quick reordering.": "بعد تنفيذ الطلب يمكن أن تظهر منتجاته هنا لإعادة الشراء سريعاً.",
  "WELCOME BACK.": "مرحباً بعودتك.", "WELCOME": "مرحباً", "BACK.": "بعودتك.",
  "Sign in to return to your Vi2 account experience, keep your shopping journey organized and make your next visit faster.": "سجّل الدخول إلى حساب Vi2 لتنظيم مشترياتك وجعل زيارتك التالية أسرع.",
  "EMAIL ADDRESS": "البريد الإلكتروني", "PASSWORD": "كلمة المرور", "New to Vi2?": "جديد لدى Vi2؟",
  "CREATE ACCOUNT": "إنشاء حساب", "ONE ACCOUNT. LESS FRICTION.": "حساب واحد. تجربة أسهل.",
  "A cleaner account experience designed around faster return visits, saved preferences and a simpler Vi2 journey.": "تجربة حساب أبسط لزيارات أسرع وتفضيلات محفوظة ورحلة أسهل مع Vi2.",
  "Keep purchases together.": "اجمع مشترياتك في مكان واحد.", "VI2 REWARDS": "مكافآت Vi2",
  "Member benefits ready for later.": "مزايا الأعضاء جاهزة للمستقبل.", "FASTER RETURN": "عودة أسرع",
  "Get back to your routine quickly.": "عُد إلى روتينك بسرعة.", "VI2 ACCOUNT EXPERIENCE": "تجربة حساب Vi2",
  "Enter your email and password.": "أدخل بريدك الإلكتروني وكلمة المرور.",
  "No account with this email exists on this browser yet.": "لا يوجد حساب بهذا البريد على هذا المتصفح بعد.",
  "Could not sign in.": "تعذر تسجيل الدخول.", "Signed in. Opening your account...": "تم تسجيل الدخول. جارٍ فتح حسابك...",
  "SIGNING IN...": "جارٍ تسجيل الدخول...", "JOIN VI2": "انضم إلى Vi2", "CREATE ACCOUNT.": "أنشئ حساباً.",
  "Create your Vi2 account experience for a faster return, saved details and future member features.": "أنشئ حساب Vi2 لعودة أسرع وبيانات محفوظة ومزايا أعضاء مستقبلية.",
  "FIRST NAME *": "الاسم الأول *", "First name": "الاسم الأول", "LAST NAME *": "اسم العائلة *", "Last name": "اسم العائلة",
  "MOBILE NUMBER *": "رقم الهاتف المحمول *", "EMAIL ADDRESS *": "البريد الإلكتروني *", "PASSWORD *": "كلمة المرور *",
  "8+ CHARACTERS": "٨ أحرف أو أكثر", "KEEP IT UNIQUE": "اجعلها مميزة", "CONFIRM PASSWORD *": "تأكيد كلمة المرور *",
  "Repeat password": "أعد كتابة كلمة المرور", "I agree to create a Vi2 account experience using these details on this browser.": "أوافق على إنشاء حساب Vi2 بهذه البيانات على هذا المتصفح.",
  "Already have an account?": "لديك حساب بالفعل؟", "CREATING ACCOUNT...": "جارٍ إنشاء الحساب...",
  "Complete all required fields.": "أكمل جميع الحقول المطلوبة.", "Enter a valid Egyptian mobile number.": "أدخل رقم هاتف مصرياً صحيحاً.",
  "Your password must be at least 8 characters.": "يجب ألا تقل كلمة المرور عن ٨ أحرف.", "The passwords do not match.": "كلمتا المرور غير متطابقتين.",
  "Accept the account terms to continue.": "وافق على شروط الحساب للمتابعة.", "Your Vi2 account is ready.": "حسابك على Vi2 جاهز.",
  "JOIN THE VI2 ROUTINE.": "انضم إلى روتين Vi2.",
  "A simple member experience built around your routine, without connecting any backend yet.": "تجربة عضوية بسيطة تتمحور حول روتينك، دون تغيير السلوك التجريبي الحالي.",
  "MEMBER BENEFITS": "مزايا الأعضاء", "Ready for rewards later.": "جاهزة للمكافآت مستقبلاً.",
  "Ready for backend connection later.": "جاهز للربط مستقبلاً.", "YOUR ROUTINE": "روتينك",
  "Make repeat shopping simpler.": "اجعل تكرار الشراء أسهل.", "VI2 IDENTITY": "هوية Vi2",
  "One clean account journey.": "رحلة حساب واحدة وسلسة.", "FRONTEND ACCOUNT FLOW": "تجربة حساب تجريبية",
  "THE VI2 BRAND EDIT": "مختارات علامات Vi2", "BRANDS A–Z": "العلامات من أ إلى ي",
  "Browse the supplement and wellness brands curated for Vi2.": "تصفح علامات المكملات والعافية المختارة لدى Vi2.",
  "CURATED BRANDS": "علامات مختارة", "VI2 BRANDS": "علامات Vi2", "SHOP BY BRAND": "تسوق حسب العلامة", "NEW": "جديد",
  "MOST-LOVED AT VI2": "الأكثر شعبية لدى Vi2", "BEST SELLERS.": "الأكثر مبيعاً.",
  "The products customers keep coming back to — ranked by popularity, ratings and demand across the Vi2 catalog.": "المنتجات التي يعود إليها العملاء باستمرار، مرتبة حسب الشعبية والتقييمات والطلب في كتالوج Vi2.",
  "Omega & Fish Oils": "أوميجا وزيوت السمك", "ADD": "أضف",
  "NO PRODUCTS IN THIS CATEGORY YET.": "لا توجد منتجات في هذه الفئة بعد.", "VIEW ALL BEST SELLERS": "عرض كل الأكثر مبيعاً",
  "DAILY ROTATION": "اختيارات يومية متجددة", "FLASH DEALS.": "عروض سريعة.", "REFRESHES DAILY": "تتجدد يومياً",
  "FLASH PICK": "اختيار العرض", "A rotating edit of popular products without adding another oversized hero carousel.": "مختارات متجددة من المنتجات الرائجة بعروض يومية بسيطة.",
  "VI2 COMPLETE CATALOG": "كتالوج Vi2 الكامل", "BROWSE EVERY CATEGORY": "تصفح كل الفئات",
  "Close search": "إغلاق البحث", "SEARCH VI2": "ابحث في Vi2", "Product, brand, health goal...": "منتج، علامة تجارية، هدف صحي...",
  "RECENT SEARCHES": "عمليات البحث الأخيرة", "POPULAR SEARCHES": "الأكثر بحثاً", "SUGGESTED RESULTS": "نتائج مقترحة",
  "POPULAR PICKS": "اختيارات شائعة", "VIEW ALL RESULTS": "عرض كل النتائج", "CLEAR": "مسح",
  "Try another product, brand, category or health goal.": "جرّب منتجاً أو علامة أو فئة أو هدفاً صحياً آخر.",
  "Close menu": "إغلاق القائمة", "VIEW ALL BRANDS": "عرض كل العلامات", "SHOP VI2": "تسوق من Vi2",
  "FLASH DEALS": "عروض سريعة", "VALUE SETS": "الباقات الموفّرة",
  "MORE THAN": "أكثر من", "SUPPLEMENTS": "مكملات", "PREMIUM SUPPLEMENTS": "مكملات متميزة",
  "FOR A STRONGER, HEALTHIER YOU.": "لحياة أقوى وأكثر صحة.", "START WITH": "ابدأ بـ",
  "WHAT YOU NEED.": "ما تحتاجه.", "Real health.": "صحة حقيقية.", "Real progress.": "تقدم حقيقي.",
  "A stronger you.": "نسخة أقوى منك.", "STRONGER": "أقوى", "EVERYDAY": "كل يوم",
  "BUILD A": "ابنِ", "ROUTINE.": "روتينك.", "THE ROUTINE.": "روتينك.",
  "BEST": "الأكثر", "SELLERS.": "مبيعاً.", "FLASH": "عروض", "DEALS.": "سريعة.",
  "CURATED": "مختارة", "BRANDS": "علامات", "product": "منتج", "products": "منتجات",
  "Optional delivery instructions": "تعليمات توصيل اختيارية", "Your password": "كلمة المرور",
  "Create password": "أنشئ كلمة مرور", "Show password": "إظهار كلمة المرور", "Hide password": "إخفاء كلمة المرور",
  "serving": "حصة", "Breadcrumb": "مسار التنقل", "Show product": "عرض المنتج",
  "Show product facts": "عرض حقائق المنتج", "Show package details": "عرض تفاصيل العبوة",
  "Show quality details": "عرض تفاصيل الجودة", "Save product": "حفظ المنتج", "Share product": "مشاركة المنتج",
  "VI2 QUALITY": "جودة Vi2", "QUALITY FIRST.": "الجودة أولاً.",
  "Authenticity, batch and supporting product information are organized in one place.": "معلومات الأصالة والتشغيلة والبيانات الداعمة للمنتج منظمة في مكان واحد.",
  "Package format shown exactly as listed in the Vi2 catalog.": "شكل العبوة معروض كما هو مسجل في كتالوج Vi2.",
  "SIZE": "الحجم", "See package": "راجع العبوة",
  "Full ingredient panels can be connected when the final supplier catalog is provided.": "يمكن إضافة جداول المكونات الكاملة عند توفير كتالوج المورد النهائي.",
  "Certificate / COA area": "قسم الشهادة / تحليل COA", "Batch & expiry area": "قسم التشغيلة والصلاحية",
  "Regulatory status area": "قسم الحالة التنظيمية",
  "Delivery pricing is shown before the order is placed. Orders over 2,500 EGP receive free delivery.": "يظهر سعر التوصيل قبل تأكيد الطلب. تحصل الطلبات فوق ٢٬٥٠٠ جنيه على توصيل مجاني.",
  "Review moderation and verified-purchase checks will connect to customer accounts in the final platform.": "سيتم ربط مراجعة المحتوى والتحقق من الشراء بحسابات العملاء في المنصة النهائية.",
  "Tell other shoppers about your experience...": "أخبر المتسوقين الآخرين عن تجربتك...",
  "LAST QTY:": "آخر كمية:",
  "Mobile navigation": "التنقل على الهاتف", "Choose hero slide": "اختر شريحة العرض",
  "Whole-body daily support for men in a simple daily multivitamin format.": "دعم يومي شامل للرجال في تركيبة بسيطة من الفيتامينات المتعددة.",
  "Micronized creatine for strength, performance and muscle-focused training routines.": "كرياتين ميكرونايزد لدعم القوة والأداء وروتينات التدريب الموجهة للعضلات.",
  "Glutamine powder formulated for recovery-focused sports nutrition routines.": "مسحوق جلوتامين مصمم لروتينات التغذية الرياضية الداعمة للاستشفاء.",
  "An omega supplement created for a simple everyday wellness routine.": "مكمل أوميجا مصمم لروتين عافية يومي بسيط.",
  "Whey protein created for convenient everyday sports nutrition.": "بروتين واي مصمم لتغذية رياضية يومية سهلة.",
  "Doctor's Best High Absorption Magnesium, 120 tablets, 100 mg per tablet.": "مغنيسيوم عالي الامتصاص من Doctor's Best، ١٢٠ قرصاً، ١٠٠ ملجم لكل قرص.",
  "NOW Foods Omega-3 fish oil in a 200-softgel bottle.": "زيت سمك أوميجا-3 من NOW Foods في عبوة ٢٠٠ كبسولة هلامية.",
  "California Gold Nutrition Vitamin D3, 125 mcg (5,000 IU), 90 fish gelatin softgels.": "فيتامين D3 من California Gold Nutrition بتركيز ١٢٥ ميكروجرام (٥٬٠٠٠ وحدة)، ٩٠ كبسولة هلامية.",
  "NOW Foods Ultra Omega-3 fish oil in a convenient softgel format.": "زيت سمك ألترا أوميجا-3 من NOW Foods في كبسولات هلامية سهلة الاستخدام.",
  "Marine-sourced hydrolyzed collagen peptides with hyaluronic acid and vitamin C, unflavored.": "ببتيدات كولاجين بحري متحللة مع حمض الهيالورونيك وفيتامين C، دون نكهة.",
  "USP-grade vitamin C, 1,000 mg per veggie capsule, in a 60-capsule bottle.": "فيتامين C بدرجة USP، ١٬٠٠٠ ملجم لكل كبسولة نباتية، عبوة ٦٠ كبسولة.",
  "NOW Foods Zinc Picolinate, 50 mg, in a 120 veggie-capsule bottle.": "زنك بيكولينات من NOW Foods بتركيز ٥٠ ملجم، عبوة ١٢٠ كبسولة نباتية.",
  "NOW Foods Sports creatine monohydrate, 0.75 g per capsule, 120 veggie capsules.": "كرياتين مونوهيدرات الرياضي من NOW Foods، ٠٫٧٥ جم لكل كبسولة، ١٢٠ كبسولة نباتية.",
  "NOW Foods standardized ashwagandha extract, 450 mg, 90 veggie capsules.": "مستخلص أشواجاندا معياري من NOW Foods، ٤٥٠ ملجم، ٩٠ كبسولة نباتية.",
  "California Gold Nutrition LactoBif 30 probiotics with 30 billion CFU per veggie capsule.": "بروبيوتك LactoBif 30 من California Gold Nutrition مع ٣٠ مليار وحدة لكل كبسولة نباتية.",
  "California Gold Nutrition CoQ10, 100 mg, in tapioca-based veggie softgels.": "CoQ10 من California Gold Nutrition بتركيز ١٠٠ ملجم في كبسولات نباتية هلامية.",
  "Optimum Nutrition Gold Standard 100% Whey Protein, Chocolate Malt, 2 lb (907 g).": "Gold Standard واي بروتين ١٠٠٪ من Optimum Nutrition بنكهة شوكولاتة مالت، ٢ رطل (٩٠٧ جم).",
  "Unflavored creatine monohydrate delivering 5,000 mg (5 g) per serving for strength, power and high-intensity training performance.": "كرياتين مونوهيدرات دون نكهة يوفر ٥٬٠٠٠ ملجم (٥ جم) لكل حصة لدعم القوة والأداء في التدريب عالي الكثافة.",
};

const arabicBySlug: Record<string, string> = {
  "for-him-multivitamin": "ملتي فيتامين متعدد الفيتامينات للرجال صحة يومية",
  "nutri-nations-creatine": "كرياتين كرياتين مونوهيدرات قوة عضلات",
  "nutri-nations-glutamine": "جلوتامين استشفاء عضلات هضم",
  "omega-x": "أوميجا اوميغا زيت سمك قلب", "whey-x": "واي بروتين مصل اللبن شوكولاتة عضلات",
  "doctors-best-high-absorption-magnesium": "مغنيسيوم امتصاص عالي نوم استرخاء",
  "now-foods-omega-3-200-softgels": "أوميجا 3 اوميغا زيت السمك قلب",
  "california-gold-vitamin-d3-5000": "فيتامين د د3 مناعة عظام",
  "now-foods-ultra-omega-3": "أوميجا اوميغا زيت سمك قلب",
  "california-gold-collagenup-206g": "كولاجين بشرة شعر أظافر",
  "california-gold-gold-c-vitamin-c-1000": "فيتامين سي ج مناعة", "now-foods-zinc-picolinate-50": "زنك مناعة",
  "now-foods-creatine-capsules": "كرياتين كبسولات عضلات", "now-foods-ashwagandha-450": "أشواجاندا اشواغاندا توتر نوم",
  "california-gold-lactobif-30": "بروبيوتك بكتيريا نافعة هضم أمعاء", "california-gold-coq10-100": "كيو 10 كوإنزيم قلب طاقة",
  "optimum-nutrition-gold-standard-whey-chocolate-malt": "واي بروتين مصل اللبن شوكولاتة عضلات",
  "big-ramy-labs-red-rex-creatine-5000mg": "كرياتين ريد ريكس عضلات قوة",
};

export function getArabicProductSearchText(product: Product) {
  const categoryAliases: Record<string, string> = {
    Protein: "بروتين واي مصل اللبن عضلات", Creatine: "كرياتين قوة عضلات",
    Vitamins: "فيتامين فيتامينات معادن مناعة", Wellness: "عافية صحة يومية",
    "Pre-Workout": "قبل التمرين طاقة أداء", "Mass Gainer": "زيادة الوزن الكتلة ماس جينر",
  };
  return ["مكمل مكملات صحة عافية تغذية رياضية منتجات", arabicBySlug[product.slug] ?? "", categoryAliases[product.category] ?? ""].join(" ");
}

export function translateArabicUi(value: string) {
  const normalized = value.replace(/\s+/g, " ").trim();
  if (!normalized) return value;
  const direct = arabicUi[normalized];
  if (direct) return direct;
  const productCount = normalized.match(/^(\d+) PRODUCTS?$/i);
  if (productCount) return `${productCount[1]} منتج`;
  const brandCount = normalized.match(/^(\d+) products?$/i);
  if (brandCount) return `${brandCount[1]} منتج`;
  const remaining = normalized.match(/^ONLY (\d+) LEFT$/i);
  if (remaining) return `متبقي ${remaining[1]} فقط`;
  const ratings = normalized.match(/^(\d+(?:[.,]\d+)?[KM]?) ratings$/i);
  if (ratings) return `${ratings[1]} تقييم`;
  const lastQuantity = normalized.match(/^LAST QTY:\s*(\d+)$/i);
  if (lastQuantity) return `آخر كمية: ${lastQuantity[1]}`;
  const deliveryRemaining = normalized.match(/^([\d,.]+) EGP TO GO$/i);
  if (deliveryRemaining) return `متبقي ${deliveryRemaining[1]} جنيه`;
  const showProducts = normalized.match(/^SHOW (\d+) PRODUCTS$/i);
  if (showProducts) return `عرض ${showProducts[1]} منتج`;
  const placeOrder = normalized.match(/^PLACE ORDER · ([\d,.]+) EGP$/i);
  if (placeOrder) return `تأكيد الطلب · ${placeOrder[1]} EGP`;
  const removeProduct = normalized.match(/^Remove (.+)$/);
  if (removeProduct) return `إزالة ${removeProduct[1]}`;
  const addProduct = normalized.match(/^Add (.+?)(?: to cart)?$/);
  if (addProduct) return `إضافة ${addProduct[1]}`;
  const viewProduct = normalized.match(/^View (.+)$/);
  if (viewProduct) return `عرض ${viewProduct[1]}`;
  const showSlide = normalized.match(/^Show slide (\d+)$/i);
  if (showSlide) return `عرض الشريحة ${showSlide[1]}`;
  const unitText = normalized
    .replace(/\bVeggie Softgels\b/g, "كبسولات نباتية هلامية")
    .replace(/\bVeggie Capsules\b/g, "كبسولات نباتية")
    .replace(/\bVeg Capsules\b/g, "كبسولات نباتية")
    .replace(/\bSoftgels\b/g, "كبسولات هلامية")
    .replace(/\bTablets\b/g, "أقراص")
    .replace(/\bCapsules\b/g, "كبسولات")
    .replace(/\bChocolate Malt\b/g, "شوكولاتة مالت")
    .replace(/\bChocolate\b/g, "شوكولاتة")
    .replace(/\bUnflavored\b/g, "دون نكهة");
  const localizedUnits = unitText.replace(/\bserving\b/gi, "حصة");
  if (localizedUnits !== normalized) return localizedUnits;
  return value;
}
